getBookings:
  path: /booking
  controller: App\Controller\BookingController::index
  methods: [GET]

getResourceTypes:
  path: /booking/getResourceTypes
  controller: App\Controller\BookingController::getResourceTypes
  methods: [GET]

getResourceFromType:
  path: /booking/getResourceFromType/{id}
  controller: App\Controller\BookingController::getResourceFromType
  methods: [GET]

makeBooking:
  path: /booking/makeBooking
  controller: App\Controller\BookingController::makeBooking
  methods: [POST]

getScheduleFromResource:
  path: /booking/getScheduleFromResource
  controller: App\Controller\BookingController::getScheduleFromResource
  methods: [POST]

renderBookings:
  path: /booking/{id}
  controller: App\Controller\BookingController::renderBookings
  methods: [POST]