getDisciplineParts:
  path: /disciplinePart
  controller: App\Controller\DisciplinePartController::index
  methods: [GET]

makeMeasure:
  path: /disciplinePart/makeMeasure
  controller: App\Controller\DisciplinePartController::makeMeasure
  methods: [PUT]

createDisciplinePartView:
  path: /disciplinePart/create
  controller: App\Controller\DisciplinePartController::createDisciplinePartView
  methods: [GET]

createDisciplinePart:
  path: /disciplinePart/create
  controller: App\Controller\DisciplinePartController::createDisciplinePart
  methods: [POST]