getMessages:
  path: /message
  controller: App\Controller\MessageController::index
  methods: [GET]

deleteMessage:
  path: /message/{id}
  controller: App\Controller\MessageController::delete
  methods: [DELETE]

getAllMessagesCount:
  path: /message/count
  controller: App\Controller\MessageController::getAllMessagesCount
  methods: [GET]

deleteAllNotifications:
  path: /notification
  controller: App\Controller\NotificationController::deleteAll
  methods: [DELETE]