getMessages:
  path: /message
  controller: App\Controller\MessageController::index
  methods: [GET]

getAllMessagesCount:
  path: /message/count
  controller: App\Controller\MessageController::getAllMessagesCount
  methods: [GET]

markImportantMessage:
  path: /message/markImportantMessage/{id}
  controller: App\Controller\MessageController::markImportant
  methods: [PUT]

markReadedMessage:
  path: /message/markReadedMessage/{id}
  controller: App\Controller\MessageController::markReaded
  methods: [PUT]

deleteSelectedMessages:
  path: /message/deleteSelectedMessages
  controller: App\Controller\MessageController::deleteSelectedMessages
  methods: [DELETE]

deleteMessage:
  path: /message/{id}
  controller: App\Controller\MessageController::delete
  methods: [DELETE]

createViewMessage:
  path: /message/create
  controller: App\Controller\MessageController::createView
  methods: [GET]

createMessage:
  path: /message/create
  controller: App\Controller\MessageController::create
  methods: [POST]