getMessages:
  path: /message
  controller: App\Controller\MessageController::index
  methods: [GET]

deleteSelectedMessages:
  path: /message/deleteSelectedMessages
  controller: App\Controller\MessageController::deleteSelectedMessages
  methods: [DELETE]

deleteMessage:
  path: /message/{id}
  controller: App\Controller\MessageController::delete
  methods: [DELETE]

getAllMessagesCount:
  path: /message/count
  controller: App\Controller\MessageController::getAllMessagesCount
  methods: [GET]